FROM qmkfm/qmk_cli

# setup with root, required for flashing
# writing /dev i.e. interacting with device bootloader requires root

# clone and setup the latest qmk_firmware, cloning into /home/qmk/qmk_firmware
RUN qmk setup -y -H /home/qmk/qmk_firmware

WORKDIR /home/qmk/qmk_firmware

# setup build environment
ENV QMK_FIRMWARE_DIR=/home/qmk/qmk_firmware
RUN apt-get update && apt-get install sudo -y
RUN . ./util/install/debian.sh && _qmk_install

COPY ./keyboards ./keyboards

CMD ["bash"]